### ISSUE TITLE
Where is the raccoon2_boinc_installer.py? build.py?

### ISSUE THREAD

**Issue by Tangbbmc** [BOINC/Raccoon2_BOINC_Plugin#3]

**Comment by AenBleidd** [comment]
@Tangbbmc, you can take the one for your OS from the releases page: https://github.com/BOINC/Raccoon2_BOINC_Plugin/releases/tag/v1.0.0

**Comment by Tangbbmc** [comment]
> @Tangbbmc, you can take the one for your OS from the releases page: https://github.com/BOINC/Raccoon2_BOINC_Plugin/releases/tag/v1.0.0

OK. Thank you for your kind help! I have successfully intalled this plugin on Window system. How do I cite this plugin when publishing paper?

**Comment by davidpanderson** [comment]
We haven't written any papers about the Raccoon2 plugin, or about BOINC Central.

The best citation would be the URL of BOINC Central, namely
https://boinc.berkeley.edu/central/

**Comment by Tangbbmc** [comment]
Ok


唐王刚 Wanggang Tang
博士 副教授 
Ph.D.  Associate Professor
Organization: Bengbu Medical College
Address: No. 2600, Donghai Avenue. Bengbu, Anhui, China






  
---- Replied Message ----
From David Anderson ***@***.***> Date 06/12/2024 06:35 To BOINC/Raccoon2_BOINC_Plugin ***@***.***> Cc Tangbbmc ***@***.***>,
Mention ***@***.***> Subject Re: [BOINC/Raccoon2_BOINC_Plugin] Where is the raccoon2_boinc_installer.py? build.py? (Issue #3)  

We haven't written any papers about the Raccoon2 plugin, or about BOINC Central.
The best citation would be the URL of BOINC Central, namely
 https://boinc.berkeley.edu/central/
